### ISSUE TITLE
dropdown menu overlaps with other menu items in toolbar

### ISSUE THREAD

**Issue by hjools** [joycechoi19/receiptAnalyzerApp#8]
When overflow button is clicked, first item of dropdown menu should be below toolbar, not on top of it 

![screenshot_20170420-144219](https://cloud.githubusercontent.com/assets/11858061/25247214/386637fc-25d8-11e7-9835-c9de8a6d63c8.png)

**Comment by joycechoi19** [comment]
tried some of these but they didn't seem to work :/ It seems like overlapping the bar is just part of it:
"Per the Material Design specifications (see the Menus section):
A menu is a temporary sheet of paper that always overlaps the app bar, rather than behaving as an extension of the app bar."

http://stackoverflow.com/questions/26638732/android-overflow-menu-positioned-above-actionbar-toolbar

http://stackoverflow.com/questions/29445584/how-i-can-place-overflow-menu-below-toolbar-instead-of-overflow-menu-to-overlaps

http://stackoverflow.com/questions/34738893/how-to-show-menu-popup-exact-below-actionbar?noredirect=1#comment57223525_34738893

http://stackoverflow.com/questions/29445584/how-i-can-place-overflow-menu-below-toolbar-instead-of-overflow-menu-to-overlaps

**Comment by hjools** [comment]
I did not know that! For some reason I thought I'd seen it below the action bar before. Maybe it has to do with the fact that I'm using a toolbar instead of the classic action bar?

I'll close this issue for now unless anybody else has any aesthetic concerns with this
